$('.reviews__slider').slick({
  dots: true,
  arrows: false,
  slidesToShow: 1,
  slidesToScroll: 1,
  infinite: true,
  autoplay: false,
  autoplaySpeed: 2000,
  speed: 2000,
  // dots: true,
  // infinite: true,
  // speed: 500,
  // fade: true,
  // cssEase: 'linear',
});
